name: CI

on:
  pull_request:
    branches:
      - main
    paths:
      - 'images/**/Dockerfile*'
      - 'templates/**/*.tf'
      - '.github/workflows/ci.yml'

  workflow_dispatch:

jobs:
  filter:
    name: Filtering
    runs-on: ubuntu-latest
    outputs:
      docker_changed: ${{ steps.filter.outputs.docker }}
      terraform_changed: ${{ steps.filter.outputs.terraform }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Path filter
      uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          docker:
            - 'images/**/Dockerfile*'
          terraform:
            - 'templates/**/*.tf'

  docker_build_test:
    name: Docker build test
    runs-on: ubuntu-latest
    needs: filter
    if: needs.filter.outputs.docker_changed == 'true'
    strategy:
      matrix:
        include:
          - platform: linux/amd64
            targetarch: amd64
          - platform: linux/arm64
            targetarch: arm64

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Dockerfile
      run: |
        docker buildx build --platform ${{ matrix.platform }} -t test-image-2204-${{ matrix.targetarch }} --output=type=oci,oci-mediatypes=true,dest=/tmp/test-image-2204-${{ matrix.targetarch }}.tar -f images/ubuntu/Dockerfile --build-arg TARGETARCH=${{ matrix.targetarch }} .

  terraform_validate:
    name: Terraform validate
    runs-on: ubuntu-latest
    needs: filter
    if: needs.filter.outputs.terraform_changed == 'true'
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: v1.10.1

    - name: Initialize Terraform
      working-directory: templates
      run: terraform init

    - name: Validate Terraform configuration
      working-directory: templates
      run: terraform validate
