name: CI

on:
  pull_request:
    branches:
      - main
    paths:
      - 'images/Dockerfile*'
      - 'templates/**/*.tf'
      - '.github/workflows/ci.yml'

  workflow_dispatch:

jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      docker_changed: ${{ steps.filter.outputs.docker }}
      terraform_changed: ${{ steps.filter.outputs.terraform }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Path filter
      uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          docker:
            - 'images/Dockerfile*'
          terraform:
            - 'templates/**/*.tf'

  docker_build_test:
    runs-on: ubuntu-latest
    needs: filter
    if: needs.filter.outputs.docker_changed == 'true'
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Dockerfile 2004
      run: docker build -t test-image-2004 -f images/Dockerfile.2004 .

    - name: Build Dockerfile 2204
      run: docker build -t test-image-2204 -f images/Dockerfile.2204 .

  terraform_validate:
    runs-on: ubuntu-latest
    needs: filter
    if: needs.filter.outputs.terraform_changed == 'true'
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.1.2

    - name: Initialize Terraform
      working-directory: templates
      run: terraform init

    - name: Validate Terraform configuration
      working-directory: templates
      run: terraform validate

  label_pr:
    runs-on: ubuntu-latest
    needs: [docker_build_test, terraform_validate]
    steps:
    - name: Remove labels
      if: ${{ needs.docker_build_test.result != 'skipped' || needs.terraform_validate.result != 'skipped' }}
      uses: actions-ecosystem/action-remove-labels@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        labels: "passing,not passing"
    - name: Add label
      if: ${{ needs.docker_build_test.result != 'skipped' || needs.terraform_validate.result != 'skipped' }}
      uses: actions-ecosystem/action-add-labels@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        labels: "${{ (needs.docker_build_test.result == 'success' || needs.terraform_validate.result == 'success') && (needs.docker_build_test.result != 'failure' && needs.terraform_validate.result != 'failure') && 'passing' || (needs.docker_build_test.result == 'failure' || needs.terraform_validate.result == 'failure') && 'not passing' || '' }}"
