name: CI

on:
  pull_request:
    branches:
      - main
    paths:
      - 'images/**/Dockerfile*'
      - 'templates/**/*.tf'
      - '.github/workflows/ci.yml'

  workflow_dispatch:

jobs:
  filter:
    name: Filtering
    runs-on: ubuntu-latest
    outputs:
      docker_changed: ${{ steps.filter.outputs.docker }}
      terraform_changed: ${{ steps.filter.outputs.terraform }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Path filter
      uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          docker:
            - 'images/**/Dockerfile*'
          terraform:
            - 'templates/**/*.tf'

  docker_build_test:
    name: Docker build test
    runs-on: ubuntu-latest
    needs: filter
    if: needs.filter.outputs.docker_changed == 'true'
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Dockerfile 2204
      run: |
        docker buildx build --platform linux/amd64 -t test-image-2204-amd64 --output=type=oci,oci-mediatypes=true,dest=/tmp/test-image-2204-amd64.tar -f images/ubuntu-2204/Dockerfile.2204 --build-arg TARGETARCH=amd64 .
        docker buildx build --platform linux/arm64 -t test-image-2204-arm64 --output=type=oci,oci-mediatypes=true,dest=/tmp/test-image-2204-arm64.tar -f images/ubuntu-2204/Dockerfile.2204 --build-arg TARGETARCH=arm64 .

  terraform_validate:
    name: Terraform validate
    runs-on: ubuntu-latest
    needs: filter
    if: needs.filter.outputs.terraform_changed == 'true'
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: v1.4.4

    - name: Initialize Terraform
      working-directory: templates
      run: terraform init

    - name: Validate Terraform configuration
      working-directory: templates
      run: terraform validate
