name: Docker Build and Push to Hub

on:
  push:
    tags:
      - 'v*'

  workflow_dispatch:

  schedule:
    - cron: '0 4 * * *'

jobs:

  ubuntu-buildpush:
    name: Ubuntu Build and Push
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4.1.5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: GitHub Container Registry Login
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5.3.0
        with:
          context: ./images
          file: ./images/ubuntu/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/mxnet-dev/ubuntu-dev:latest

  delete-versions:
    name: Delete old packages
    runs-on: ubuntu-latest
    steps:

      - uses: actions/delete-package-versions@v5
        with:
          package-name: 'ubuntu'
          package-type: 'container'
          min-versions-to-keep: 3