name: Docker Build and Push to Hub

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

  workflow_dispatch:

  schedule:
    - cron: '0 4 * * *'

defaults:
  run:
    working-directory: images

jobs:

  ubuntu-2004-buildpush:
    name: Ubuntu 20.04 Build and Push
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3.0.2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.0.0

      - name: GitHub Container Registry Login
        uses: docker/login-action@v2.0.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v3.1.1
        with:
          platforms: linux/amd64,linux/arm64
          file: Dockerfile.2004
          push: true
          tags: ghcr.io/mxnet-dev/ubuntu:2004


  ubuntu-2204-buildpush:
    name: Ubuntu 22.04 Build and Push
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3.0.2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.0.0

      - name: GitHub Container Registry Login
        uses: docker/login-action@v2.0.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v3.1.1
        with:
          platforms: linux/amd64,linux/arm64
          file: Dockerfile.2204
          push: true
          tags: ghcr.io/mxnet-dev/ubuntu:2204